//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint_DB
    {
        public int Complaint_ID { get; set; }
        public string Date { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public string User_Name { get; set; }
        public string User_Email { get; set; }
        public string Status { get; set; } = "Pending";
    
        public virtual Complaint_DB Complaint_DB1 { get; set; }
        public virtual Complaint_DB Complaint_DB2 { get; set; }
    }
}
